# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('lat', models.CharField(blank=True, max_length=10, null=True)),
                ('lon', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('tz', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('elev', models.CharField(blank=True, max_length=20, null=True)),
                ('direct_flights', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'mmt',
                'managed': False,
            },
        ),
    ]
